### ISSUE TITLE
Does LLM performs better than BERT-CRF?

### ISSUE THREAD

**Issue by eshoyuan** [poteminr/medner#2]
Can you share your result? Thank you!

**Comment by poteminr** [comment]
Hi! 
The main goal of this research is to use LLMs for Nested NER task to remove some disadvantages of  encoder-based models.  My next step is applying LLM to datasets with nested entities.

In my opinion, there is no reason to apply LLMs for Flat-NER (classic NER) due to expensive computations with the same or worse perfomance. I prefer to use BERT-CRF with some additions like contrastive learning for FLAT-NER.

**Comment by eshoyuan** [comment]
Thank you.
